### ISSUE TITLE
Vytvoriť návrh

### ISSUE THREAD

**Issue by zuzhal** [TIS2018-FMFI/urychlovac#10]

**Comment by kovac254** [comment]
Zaciatocna cast navrhu v prilohe
[Navrh.docx](https://github.com/TIS2018-FMFI/urychlovac/files/2569535/Navrh.docx)

**Comment by danshaman05** [comment]
aktualna verzia (Google Docs)
https://docs.google.com/document/d/1OEuMU-U7svWp4oEKitzGWLskseAVFzZ1h7rgEjxrOrw/edit?usp=sharing

**Comment by pavelpetrovic** [comment]
zo stretnutia

trochu zlepsit issues, mali by byt o vsetkom, co sa na projekte deje, implementuje, ...
--
navrhu gui prosim prediskutovat aj so zadavatelom osobne
 
pripravit testovacie scenare
co najskor doriesit vsetky technologicke otazky
implementaciu priebezne komitovat na github
dotiahnut drobne posledne upravy v navrhu
