### ISSUE TITLE
Návrh implementácie

### ISSUE THREAD

**Issue by zuzhal** [TIS2018-FMFI/urychlovac#13]
Zrozumiteľný a jednoznačný návrh implementácie, podľa ktorého sa dá aplikácia vyvinúť a ktorý bude obsahovať: UML component diagram, UML class diagram, a aspoň jeden z dvojice UML state a UML sequence diagram, zrozumiteľne vysvetlenú architektúru, rozdelenie na časti (moduly) a ich interfejsy, využité technológie, cieľové prostredie nasadenia do prevádzky.

**Comment by danshaman05** [comment]
linky k editacii momentalnych verzii grafov: 
D. use-case: https://drive.google.com/file/d/1rLpgucpTBpLfRCs9wo9JyuNX8kyELRsO/view?usp=sharing
D. komponentov: https://drive.google.com/file/d/1aqyNxx58wGWK_YDWZQ3SH6ANg-hQxIOI/view?usp=sharing

**Comment by pavelpetrovic** [comment]
Michal K | riesil triedny diagram |  
Michal P | bude o tyzden referovat aky velky prinos do projektu vlozil |  
Daniel | implentoval konfiguracny subor |  
Zuzana | je na stretnuti so zadavatelom |  

prediskutovali sme triedny diagram |   
nasleduje otestovanie realnych hardverovych komponentov a integrovanie do projektu |   
praca je rozdelena |   
nabuduce uz bude navrh vo finalnej verzii schvaleny na githube |   
testovacie scenare budu takmer hotove |   
a na gite bude nejaky kod aj v master branchi |
