### ISSUE TITLE
Implementacia digitalizovania hodnot arduinom a ich odoslanie cez seriovy port

### ISSUE THREAD

**Issue by kovac254** [TIS2018-FMFI/urychlovac#16]
Treba naprogramovat Arduino tak, aby precitalo hodnotu zo senzoru a odoslalo ju v rozumnej podobe na dalsie spracovanie Javackemu backendu.

**Comment by pavelpetrovic** [comment]
ak treba, mozem vam na toto pozicat cvicny hardver.
