### ISSUE TITLE
Vytvoriť katalóg požiadaviek

### ISSUE THREAD

**Issue by empi7** [TIS2018-FMFI/urychlovac#4]
Treba spísať katalóg požiadaviek a dať na kontrolu zadávateľovi.

**Comment by kovac254** [comment]
Pan Petrovic poslal pripomienky, treba ich zapracovat a katalog moze ist na schvalenie k zadavatelovi.

**Comment by kovac254** [comment]
Pripomienky su zapracovane.

GSM modul v katalogu chyba, lebo sme sa so zadavatelom dohodli, ze to nebude oficialna poziadavka na informacny system.

Koncovky "ii" som presiel a nenasiel som v nich ziadne chyby. Mohli by ste prosim upresnit alebo dat priklad, co s nimi myslite?

[Katalog_poziadaviek_RC3.pdf](https://github.com/TIS2018-FMFI/urychlovac/files/2522573/Katalog_poziadaviek_RC3.pdf)

**Comment by pavelpetrovic** [comment]
Dakujem, je to pekne.  Nie celkom este rozumiem tomuto: 

"Systém vyžaduje použitie statických IP adries na lokálnej sieti."

Asi mate na mysli iba kamery, tak by to tam malo byt uvedene a asi to nie je az take nutne aby to boli adresy na lokalnej sieti, vas system bude fungovat, aj ked to budu normalne IP adresy na internete, takze by som to preformuloval napr. "Systém predpokladá, že IP kamery budú mať nastavené statické IP adresy."
Podobne: "back end systému vyžaduje Java Runtime Environment 11+"
Pochybujem, ze vyuzijete nejake features java 11, skor by som uviedol, ze garantujete, ze bude fungovat v tejto verzii, nie ze ju vyzaduje.

Myslim si, ze by bolo dost uzitocne, aby sa logovali aj dvojhodnotove merania - aby sa jednoducho niekde zaznamenalo a neskor dalo pozriet, kedy bol aky vypadok, otvorene dvere a pod. mozno by to mohol byt treti subor, v  ktorom sa zaznamena cas a slovo urcujuce typ udalosti.

Ohladne GSM modulu - presne na toto sa da nastavit priorita poziadaviek, pouzili to aj ine skupiny. Oznacte poziadavky prioritou - ktore su nutne a ktore su fakultativne.
Malo by to tam byt uvedene, aj ked je to len fakultativna poziadavka, aby bolo jasne, co sa od toho ocakava a neintegrovalo sa to neskor v chaose bez premyslenia vopred.

koncovky ii:

- vzniknutej situácií.
- o krízovej situácií

6. pad, singular
http://slovnik.azet.sk/pravopis/?q=situ%C3%A1cia
vynájsť sa v každej s-ii 

Poupravujte teda, prosim, co sa da a potom to poslite zadavatelovi a poziadajte ho, aby si to dokument precital, a dal pripadne spatnu vazbu, co este upravit, lebo podla toho to vyviniete. Potrebujem jeho formalny suhlas, ze si dokument prestudoval a finalna verzia zachytava ich poziadavky. Vela zdaru!

**Comment by kovac254** [comment]
Pripajam finalnu verziu katalogu poziadaviek. Zadavatel ju záväzne schvalil.

[Katalog_poziadaviek_RC4.pdf](https://github.com/TIS2018-FMFI/urychlovac/files/2543292/Katalog_poziadaviek_RC4.pdf)
