### ISSUE TITLE
Vytvoriť podrobnú špecifikáciu vonkajších interfejsov

### ISSUE THREAD

**Issue by zuzhal** [TIS2018-FMFI/urychlovac#9]
Je potrebné, v návrhu, vytvoriť podrobnú špecifikáciu vonkajších interfejsov - ak aplikácia komunikuje s inými aplikáciami, súbormi, zariadeniami - tieto musia byť jasne a podrobne definované

**Comment by danshaman05** [comment]
Navod pre GSM Shield:
https://navody.arduino-shop.cz/navody-k-produktum/arduino-gsm-shield-sim900.html
